---
# tasks file for postgresql

- name: installing postgresql rpm from a remote repo
  yum:
    name: https://yum.postgresql.org/9.4/redhat/rhel-7-x86_64/pgdg-centos94-9.4-2.noarch.rpm
    state: present

- name: updataing packages
  yum: 
    name: '*'
    state: latest

- name: installing the postgresql94 
  yum: 
    name: "{{ item }}"
    state: present
  with_items:
    - postgresql94-server
    - postgresql94-contrib

- name: installing initdb 
  command: "/usr/pgsql-9.4/bin/postgresql94-setup initdb"
  args:
      creates: "/var/lib/pgsql/9.4/initdb.log"

- name: starting postgresql94
  service:
    name: postgresql-9.4
    enabled: yes
    state: started

- name: update postgres client authentication config file
  template:
    src: pg_hba.conf.j2
    dest: /var/lib/pgsql/9.4/data/pg_hba.conf
    mode: 0644
  notify: restart postgresql

- name: update postgres config file
  template:
    src: postgresql.conf.j2
    dest: /var/lib/pgsql/9.4/data/postgresql.conf 
    mode: 0644
  notify: restart postgresql

- name: restarting postgresql
  service:
    name: postgresql-9.4
    state: restarted

- name: installing python extra package
  yum: 
    name: python-psycopg2
    state: present  

- name: creating postgres user
  postgresql_user:
    name: "{{ user_name }}"
    password: "{{ passwd }}"
    role_attr_flags: SUPERUSER

- name: creating postgres database
  postgresql_db:
    name: "{{ db_name }}"
    encoding: UTF8
    lc_collate: en_US.UTF-8
    lc_ctype: en_US.UTF-8
    owner: mystique
    template: template0
