---
# tasks file for java
- name: installing java on Redhat
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ Redhat_java }}"
  when: ansible_os_family == "RedHat"
- name: Exporting path 
  template:
    src: profile.j2
    dest: /etc/profile
    mode: 0644 
