---
# tasks file for node.js
- name: Updating/installing nodes package
  yum:
    name:  https://rpm.nodesource.com/pub_4.x/el/7/x86_64/nodesource-release-el7-1.noarch.rpm
    state: present
  
- name: installing nodejs
  yum: 
    name: nodejs
    state: present
# create a directory if it doesn't exist
- file:
    path: ~/.local/bin/npm
    state: directory
    mode: 0755

- name: insttaling npm packages
  npm:
    name: "{{ item }}"
    state: present
    global: yes
  with_items:
    - "{{ npm_pack }}"
