---
# tasks file for ruby
- name: installing Extra packages
  yum:
    name: "{{ item }}"
    state: present
  with_items: 
    - "{{ package }}"

# Installs latest available version of rake.

- gem:
    name: rake
    state: present 

# Installs latest available version of selenium-client.

- gem:
    name: selenium-client 
    state: present
